version: "2"
run:
  build-tags:
    - conformance
linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - errorlint
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    gocyclo:
      min-complexity: 20
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - noctx
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/OpScaleHub/cert-manager-webhook-arvancloud
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
