run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/OpScaleHub/cert-manager-webhook-arvancloud
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0
