apiVersion: v1
kind: Service
metadata:
  name: {{ include "arvancloud-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arvancloud-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "arvancloud-webhook.selectorLabels" . | nindent 4 }}
